### PR TITLE
Add AQAvit and Temurin project leads to view security reports

### PR DESCRIPTION
**Pull request by gdams**

### CODE REVIEW

**Review by smlambert — APPROVED** [review]

**Comment by tellison** [comment]
I prefer that we create a new group explicitly for visibility of the security vulnerabilities, eg `adoptium-vulnerability-team`

(I note that Eclipse use "security team" but security is a broad term and includes development work unrelated to this role)

**Comment by mbarbero** [comment]
> I prefer that we create a new group explicitly for visibility of the security vulnerabilities, eg `adoptium-vulnerability-team`
> 
> (I note that Eclipse use "security team" but security is a broad term and includes development work unrelated to this role)

We don't create teams other than `xxx-committers` and `xxx-project-leads` (yet). This is currently the only 2 roles that are identified in the EFDP, and any new role would need to be defined there, along with some rules to define how one get added to it.

We have a public issue if you want to discuss your requirement there https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1709.

Meanwhile, is that ok to merge and apply this change as is @tellison?

**Review by hendrikebbers — APPROVED** [review]

**Comment by tellison** [comment]
OK, we will work with what we have at the moment. I suspect we will then also need to be flexible on the definition of the groups we are permitted to use.

**Review by tellison — APPROVED** [review]

**Review by mbarbero — APPROVED** [review]

**Comment by mbarbero** [comment]
Changes have been deployed.

**Pull request merged**
