### PR TITLE
Add jdk21u adoptium mirror repo

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Create new jdk21u Adoptium mirror repository: https://github.com/adoptium/jdk21u

### CODE REVIEW

**Comment by netomi** [comment]
while looking at the change, I noticed this setting which is also enabled for the other mirror repos:

```
dependabot_security_updates_enabled: true,
```

I wonder if this makes sense for a mirror from openjdk and we should not disable that setting for all mirror repos. wdyt?

**Comment by andrew-m-leonard** [comment]
> while looking at the change, I noticed this setting which is also enabled for the other mirror repos:
> 
> ```
> dependabot_security_updates_enabled: true,
> ```
> 
> I wonder if this makes sense for a mirror from openjdk and we should not disable that setting for all mirror repos. wdyt?

@netomi I had to google what it meant, as I had just copied the previous mirrors, and yes I would agree, it would not make sense for automatic dependabot updates...

**Comment by netomi** [comment]
ok, I have updated the PR to disable dependabot alerts / updates for all mirrored repos. If you approve I merge and apply the changes.

**Comment by andrew-m-leonard** [comment]
> ok, I have updated the PR to disable dependabot alerts / updates for all mirrored repos. If you approve I merge and apply the changes.

Yes, change looks good, thanks.

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
repo has been created.

**Comment by andrew-m-leonard** [comment]
@netomi I'm struggling to mirror clone and push our jdk21 repo to this new jdk21u repo:
```
anleonar@anleonar-mac jdk21.git % git push --mirror git@github.com:adoptium/jdk21u.git
Enter passphrase for key '/Users/anleonar/.ssh/id_rsa': 
Enumerating objects: 1346049, done.
Counting objects: 100% (1346049/1346049), done.
Delta compression using up to 10 threads
Compressing objects: 100% (254542/254542), done.
Writing objects: 100% (1346049/1346049), 1.07 GiB | 2.01 MiB/s, done.
Total 1346049 (delta 1000883), reused 1346049 (delta 1000883), pack-reused 0
remote: Resolving deltas: 100% (1000883/1000883), done.
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
Connection to github.com closed by remote host.
```
I suspect because the new jdk21u repo is not "empty", we have protection to prevent the mirror push ?
Can we re-create the repo, but as an "empty" repo please?

**Pull request merged**
