### PR TITLE
Enable delete_branch_on_merge for AQA test repos

### PR DESCRIPTION
**Pull request by llxia**
resolves: https://github.com/adoptium/aqa-tests/issues/5776

### CODE REVIEW

**Review by smlambert — APPROVED** [review]
thanks @llxia !

**Comment by smlambert** [comment]
Apparently I have either lost write access or never had write permissions to this repo so can not merge this.

@netomi - Who should have write access to this repo?  Adoptium [PMC](https://projects.eclipse.org/projects/adoptium/who) members?  Or is it restricted?

**Comment by netomi** [comment]
> In order to automatically merge and apply the changes, add a comment /otterdog merge. 🚀

**Comment by smlambert** [comment]
thanks @netomi - the more words and help I am offered by bots, the less likely I am to read them... :) appreciate your patient guidance!

**Pull request merged**
