### PR TITLE
Remove unused API secrets

### PR DESCRIPTION
**Pull request by gdams**
remove secrets that are no longer needed because of https://github.com/adoptium/api.adoptium.net/commit/16210ee86758f5cc7bc51e60bd10951482931ec9

### CODE REVIEW

**Comment by netomi** [comment]
you still need to remove the parameters from the list of required inputs afaict:

https://github.com/adoptium/api.adoptium.net/blob/main/.github/actions/azure-login/action.yml#L13-L18

**Comment by gdams** [comment]
> you still need to remove the parameters from the list of required inputs afaict:
> 
> https://github.com/adoptium/api.adoptium.net/blob/main/.github/actions/azure-login/action.yml#L13-L18

good spot

**Comment by netomi** [comment]
and some deploy workflows set the parameters:

- https://github.com/adoptium/api.adoptium.net/blob/main/.github/workflows/deploy-adoptium.yml#L25-L26
- https://github.com/adoptium/marketplace-api.adoptium.net/blob/main/.github/workflows/deploy-marketplace.yml#L31-L32
- https://github.com/adoptium/api.adoptium.net/blob/main/.github/workflows/deploy-adoptium.yml#L25-L26

**Comment by gdams** [comment]
> and some deploy workflows set the parameters:
> 
> * https://github.com/adoptium/api.adoptium.net/blob/main/.github/workflows/deploy-adoptium.yml#L25-L26
> * https://github.com/adoptium/marketplace-api.adoptium.net/blob/main/.github/workflows/deploy-marketplace.yml#L31-L32
> * https://github.com/adoptium/api.adoptium.net/blob/main/.github/workflows/deploy-adoptium.yml#L25-L26

Removing them now, please proceed with the secret removal

**Review by netomi — APPROVED** [review]

**Pull request merged**
