### PR TITLE
set default branch for risc-v port mirror

### PR DESCRIPTION
**Pull request by gdams**
also tidy some other stuff

### CODE REVIEW

**Comment by netomi** [comment]
the error wrt current live settings can be ignored. The default branch can not be set if the repo is still empty, so once the mirror scripts have populated the repo the default branch can be set and then the error will go away.

**Comment by netomi** [comment]
I see now that the current default branch is riscv-port, so I guess its best to explicitly set it like that in this PR.

**Comment by gdams** [comment]
> I see now that the current default branch is riscv-port, so I guess its best to explicitly set it like that in this PR, instead of master, as otherwise riscv-port will get renamed to master, unless you want that ofc.

did I not do this?

```json
    newMirrorRepo('riscv-port-jdk11u') {
      default_branch: 'riscv-port'
    },
```

**Comment by netomi** [comment]
oh I missed that change, so then everything looks good.

**Review by netomi — APPROVED** [review]

**Pull request merged**
