### PR TITLE
Set release branch protection with approve reviews 2

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Fixes https://github.com/adoptium/temurin-build/issues/4045

Ensure build repository release branches "v*" have branch protection with 1 review required

### CODE REVIEW

**Comment by netomi** [comment]
You can be more specific about the pattern, this one would match currently 11 branches in the temurin-build repo: `v[0-9]*.[0-9]*[.+][0-9]*`

**Comment by andrew-m-leonard** [comment]
> Likely OK, but `v*` has the potential to match a broad range of branch names. Do you think it would it overcomplicate to add a more specific expression that only matches the expected pattern? I don't feel too strongly about it though

@tellison 
My initial thought was ALL branches, although it would need to be "!main", hence I just made it "v*". 

I could make it "v[0-9][0-9][0-9][0-9][\.][0-9][0-9][\.][0-9][0-9]"
but we have been known to accidently name the release branch wrongly... but still use it eg:https://github.com/adoptium/temurin-build/tree/v2024.04%2B01
so I think i'd prefer to stay with "v*"

**Comment by andrew-m-leonard** [comment]
> You can be more specific about the pattern, this one would match currently 11 branches in the temurin-build repo: `v[0-9]*.[0-9]*[.+][0-9]*`

i'd actually like to be less specific, as really ALL branches in these repos should be protected

**Review by sxa — CHANGES_REQUESTED** [review]
Blocking pending PMC discussion tomorrow (but as per the retrospective I'm personally happy with this ;-) )

**Comment by smlambert** [comment]
I am also +1 to this.  We had to ensure branch protection was turned on for aqa-tests in the past and I was surprised it was not the default template for EF projects.

**Comment by andrew-m-leonard** [comment]
@sxa @smlambert Can I get your reviews please now this has been agreed? thanks

**Review by sxa — COMMENTED** [review]
@andrew-m-leonard Could you pre-squash these commits so we don't merge this with the commit message saying 1 please? (Same for the PR description for housekeeping purposes)?

**Comment by andrew-m-leonard** [comment]
> @andrew-m-leonard Could you pre-squash these commits so we don't merge this with the commit message saying 1 please? (Same for the PR description for housekeeping purposes)?

@sxa thanks done

**Review by smlambert — APPROVED** [review]
thanks @andrew-m-leonard !

**Comment by andrew-m-leonard** [comment]
@netomi This is now ready for merging please

**Comment by netomi** [comment]
> In order to automatically merge and apply the changes, add a comment /otterdog merge. 🚀

**Pull request merged**
